var userInfoModule= angular.module("UserInfoModule",[]);
userInfoModule.controller("UserInfoCtrl",["$scope",function($scope){
	$scope.userInfo={
		email:"646732184@qq.com",
		password:"123456",
		autoLogin:true
	};
	$scope.getFormData=function(){
		console.log($scope.userInfo);
	};
	$scope.setFormData=function(){
		$scope.userInfo={
		email:"yuchan_yang@126.com",
		password:"123456789",
		autoLogin:false
	};
	}
	$scope.resetFormData=function(){
		$scope.userInfo={
		email:"646732184@qq.com",
		password:"123456",
		autoLogin:true
	};
	}
}
])